site_name: Notes
theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default # 设置浅色模式，来自 Material for MkDocs 文档
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue # 设置主色调，来自 Material for MkDocs 文档
      accent: cyan # 设置强调色，来自 Material for MkDocs 文档

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: cyan # 设置主色调，来自 Material for MkDocs 文档
      accent: blue # 设置强调色，来自 Material for MkDocs 文档
  font:
    text: Roboto Slab
    code: Roboto Mono

markdown_extensions:
  - pymdownx.arithmatex: # 公式渲染支持，来自 Material for MkDocs 文档
      generic: true
  - toc: # 目录支持，来自 Material for MkDocs 文档
      permalink: true
      baselevel: 2  # 将标题层级整体偏移1级

  # 代码块高亮支持，来自 Material for MkDocs 文档
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets

  # 提示块支持，来自 Material for MkDocs 文档
  - admonition # 提示块
  - pymdownx.details # 使提示块可折叠
  - pymdownx.superfences # 允许在提示框内嵌套代码和内容块

  # 内容标签支持，来自 Material for MkDocs 文档
  - pymdownx.tabbed: # 启用标签扩展
      alternate_style: true
  - pymdownx.superfences # 允许在标签内嵌套代码和内容块

extra_javascript:
  - /js/config.js

  # MathJax 支持，来自 Material for MkDocs 文档
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js

  # 代码高亮支持，来自 Material for MkDocs 文档
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

extra_css:
  # 代码高亮支持，来自 Material for MkDocs 文档
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true
#       type: iso_datetime #时间类型
#       timezone: Asia/Shanghai #时区
#       locale: zh #首选语言
#       fallback_to_build_date: false #许回退到git 不可用时mkdocs build执行的时间
